<h3><?php echo $this->escape($this->question['question'])?></h3>

<span><?php echo $this->escape($this->question['answer'])?></span>
<br /><br />

<span style="font-style: italic">Last update: <?php echo $this->locale()->getFormatter()->formatDateTime($this->question['datetime'], 'full-short') ?></span>
<br />

<?php if ($this->localeCount > 1): ?>
  <?php if ($this->authorizer()->isAllowed('question.update')): ?>
  <br /><a href="<?php echo $this->url(array('action' => 'update', 'item_id' => $this->question['item_id'], 'locale' => $this->question['locale']))?>">update question</a>
  <?php endif ?>
  
  <?php if ($this->authorizer()->isAllowed('question.delete')): ?>
  <br /><a href="<?php echo $this->url(array('action' => 'delete', 'item_id' => $this->question['item_id'], 'locale' => $this->question['locale']))?>">delete question</a>
  <?php endif ?>
  
  <?php if ($this->authorizer()->isAllowed('item.read')): ?>
  <br /><a href="<?php echo $this->url(array('action' => 'read', 'controller' => 'item', 'id' => $this->question['item_id']))?>">view item</a>
  <?php endif ?>
<?php else: ?>
  <?php if ($this->authorizer()->isAllowed('combined.update')): ?>
  <br /><a href="<?php echo $this->url(array('action' => 'update', 'controller' => 'combined', 'item_id' => $this->question['item_id']))?>">update combined</a>
  <?php endif ?>
  
  <?php if ($this->authorizer()->isAllowed('combined.delete')): ?>
  <br /><a href="<?php echo $this->url(array('action' => 'delete', 'controller' => 'combined', 'item_id' => $this->question['item_id']))?>">delete combined</a>
  <?php endif ?>
<?php endif ?>

<?php echo $this->partial('question/_questions.phtml', array('questions' => $this->questions)) ?>