<form method="post" action="<?php echo $this->url(array('action' => $this->action))?>">
  <?php if ($this->action == 'update'): ?>
  <input type="hidden" name="id" value="<?php echo $this->id ?>" />
  <?php endif ?>

  <dl>
    <dt><label for="label">Label</label></dt>
    <dd>
      <?php echo $this->error($this->form, 'label')?>
      <input type="text" name="form[label]" id="label" value="<?php echo $this->escape($this->form['label'])?>" />
    </dd>
  </dl>
  
  
  <dl>
    <dd>
      <input type="submit" value="<?php echo $this->action?>" />
    </dd>
  </dl>
</form>